"""update product varint model

Revision ID: 1ad52cfd2451
Revises: 01dce4b88551
Create Date: 2026-04-16 10:38:43.353174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ad52cfd2451'
down_revision: Union[str, Sequence[str], None] = '01dce4b88551'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_variant_slug', 'product_variants', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_variant_slug', 'product_variants', type_='unique')
    # ### end Alembic commands ###
