"""add order timeline

Revision ID: 71337f1bcafd
Revises: 5b6b31c7ada5
Create Date: 2026-04-13 20:12:49.767778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71337f1bcafd'
down_revision: Union[str, Sequence[str], None] = '5b6b31c7ada5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_timeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_timeline_created', 'order_timeline', ['created_at'], unique=False)
    op.create_index('idx_timeline_order', 'order_timeline', ['order_id'], unique=False)
    op.create_index('idx_timeline_status', 'order_timeline', ['status'], unique=False)
    op.create_index(op.f('ix_order_timeline_created_at'), 'order_timeline', ['created_at'], unique=False)
    op.create_index(op.f('ix_order_timeline_id'), 'order_timeline', ['id'], unique=False)
    op.create_index(op.f('ix_order_timeline_order_id'), 'order_timeline', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_timeline_status'), 'order_timeline', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_timeline_status'), table_name='order_timeline')
    op.drop_index(op.f('ix_order_timeline_order_id'), table_name='order_timeline')
    op.drop_index(op.f('ix_order_timeline_id'), table_name='order_timeline')
    op.drop_index(op.f('ix_order_timeline_created_at'), table_name='order_timeline')
    op.drop_index('idx_timeline_status', table_name='order_timeline')
    op.drop_index('idx_timeline_order', table_name='order_timeline')
    op.drop_index('idx_timeline_created', table_name='order_timeline')
    op.drop_table('order_timeline')
    # ### end Alembic commands ###
