"""fix variant FK

Revision ID: 8f0a04dab010
Revises: 65b6a8d15903
Create Date: 2026-04-13 10:21:27.941389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8f0a04dab010'
down_revision: Union[str, Sequence[str], None] = '65b6a8d15903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_items', 'variant_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint(op.f('order_items_ibfk_2'), 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'product_variants', ['variant_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key(op.f('order_items_ibfk_2'), 'order_items', 'product_variants', ['variant_id'], ['id'])
    op.alter_column('order_items', 'variant_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
