"""fix delete api

Revision ID: 98ebf14af59b
Revises: 8f0a04dab010
Create Date: 2026-04-13 10:48:56.193142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98ebf14af59b'
down_revision: Union[str, Sequence[str], None] = '8f0a04dab010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('order_items_ibfk_2'), 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'product_variants', ['variant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key(op.f('order_items_ibfk_2'), 'order_items', 'product_variants', ['variant_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
