"""add order timeline scheduler

Revision ID: ea4a4de669c3
Revises: 71337f1bcafd
Create Date: 2026-04-14 10:31:30.044753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea4a4de669c3'
down_revision: Union[str, Sequence[str], None] = '71337f1bcafd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('status_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_orders_status_updated_at'), 'orders', ['status_updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_status_updated_at'), table_name='orders')
    op.drop_column('orders', 'status_updated_at')
    # ### end Alembic commands ###
